---
app:
  name: 'Star Wars API'

httpServer:
  enabled: <%= process.env.HTTP_SERVER_ENABLED %>
  port: <%= process.env.HTTP_SERVER_PORT %>
  ssl:
    enabled: <%= process.env.HTTP_SERVER_SSL_ENABLED %>
    port: <%= process.env.HTTP_SERVER_SSL_PORT %>
    certPath: <%= process.env.HTTP_SERVER_SSL_CERT_PATH %>
    certKeyPath: <%= process.env.HTTP_SERVER_SSL_CERT_KEY_PATH %>

swagger:
  enabled: true

cors:
  enabled: true

log:
  enabled: true
  level: info
