---
app:
  name: 'Star Wars API'
  baseUrl: 'http://localhost'

httpServer:
  enabled: <%= process.env.HTTP_SERVER_ENABLED %>
  port: <%= process.env.HTTP_SERVER_PORT %>
  ssl:
    enabled: <%= process.env.HTTP_SERVER_SSL_ENABLED %>
    port: <%= process.env.HTTP_SERVER_SSL_PORT %>
    certPath: <%= process.env.HTTP_SERVER_SSL_CERT_PATH %>
    certKeyPath: <%= process.env.HTTP_SERVER_SSL_CERT_KEY_PATH %>

swagger:
  enabled: true

cors:
  enabled: true

log:
  enabled: true
  level: info

database:
  host: <%= process.env.DATABASE_HOST %>
  port: <%= process.env.DATABASE_PORT %>
  username: <%= process.env.DATABASE_USERNAME %>
  password: <%= process.env.DATABASE_PASSWORD %>
  database: <%= process.env.DATABASE_DATABASE %>

swapi:
  baseUrl: https://swapi.dev/api
