version: '3.8'

services:
  # swapi:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - 80:80
  #   env_file: .env

  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT:-15432}:5432"
    environment:
      POSTGRES_USER: "${PG_USER:-test_user}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-test_password}"
      POSTGRES_DB: "${PG_DB:-swapi}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-18080}:8080"
