version: '3.8'

services:
  swapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      replicas: 2
    restart: always
    ports:
      - "8080-8085:80"
    environment:
      HTTP_SERVER_ENABLED: true
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_SSL_ENABLED: false
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "${PG_USER:-test_user}"
      DATABASE_PASSWORD: "${PG_PASSWORD:-test_password}"
      DATABASE_DATABASE: "${PG_DB:-swapi}"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT:-15432}:5432"
    environment:
      POSTGRES_USER: "${PG_USER:-test_user}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-test_password}"
      POSTGRES_DB: "${PG_DB:-swapi}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-18080}:8080"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${ADMINER_PORT:-16379}:6379"
    command: redis-server --save 20 1 --loglevel warning
